### ISSUE TITLE
创建房源

### ISSUE THREAD

**Issue by QiDekang** [why2012/QSZ#13]
### 参数

    [province_name: string] # 省
    [province_code: number] # 省
    [city_name: string] # 市
    [city_code: number] # 市
    [county_name: string] # 区县
    [county_code: number] # 区县
    [district_name: string] # 小区
    [district_code: number] # 小区
    [house_number: number] # 门牌号
    [longitude: number] # 经纬度
    [latitude: number] # 经纬度
    //  可删除该项，目前不做短租业务。  [rent_time_type: number] #  出租方式，长租2 短租1
    [rent_room_type: number] # 出租方式，整租1 单间2
    [house_size: number] # 面积
    [house_type: string] # 户型
    [house_floor: string] # 所在楼层
    //  删除该项，需填写每个卧室的朝向，不需要再填写整个房屋的朝向了。住宅楼中整个房屋的朝向一般指主卧窗户朝向。  [house_direction: string] # 朝向
    [house_decoration: string] # 装修程度
    [house_max_livein: number] # 最大居住人数
    [house_rent: number] # 租金
    //  修改选项
    [payment_type: string] # 付款方式, 1|1 押一付一, 1|3 押一付三, 1|6 押一付六
    //  删除该项，整合到额外费用一项。  [property_management_fee: number] # 物业费归属, 1 房东, 2 租客, 3 待定
    //  删除该项，整合到额外费用一项。  [heating_charge: number] # 取暖费归属, 1 房东, 2 租客, 3 待定
    [description_title: string] # 介绍标题
    [description: string] # 特色介绍
    [traffic_condition: string] # 交通情况
    [around_condition: string] # 周边情况
    //  修改选项
    [facility: string] # 房屋设施, 1. 空调， 2. 电视， 3. 洗衣机， 4. 冰箱， 5. 微波炉， 6. 热水淋浴， 7.有线网络， 8. 无线网络， 9. 暖气， 10. 门禁系统， 11. 电梯， 12. 停车位; 1|2|3
    //  新增
    [house_source: number] # 房源类型，1. 房东直租， 2. 二房东合租， 3.租客租期内转租
    [all_floor: number] # 全部楼层
    [earliest_checkin_time: string] # 最早入住时间
    [release_time: string] # 发布时间
    [submission_time: string] # 提交审核时间
    [extra_fee: string] # 额外费用。 1. 水费， 2. 电费， 3. 燃气费， 4. 网费， 5. 取暖费， 6. 卫生费， 7. 电视费， 8. 物业费； 1|2|3

**Comment by why2012** [comment]
Done.

**Comment by QiDekang** [comment]
**新增字段**
[subdistrict_name: string] # 街道名称
[building_number: string] # 楼号
[unit_number: string] # 单元号
[subway_line_name: string] # 地铁线路名称
[subway_line_code: string] # 地铁线路编码
[subway_station_name: string] # 地铁站名称
[collections_number: number] # 被收藏的次数
[nearest_subway_distance: number]  # 最近地铁站距离

**修改字段**
[county_name: string] # 区县  ==>  [district_name: string] # 区县
[county_code: number] # 区县  ==>  [district_code: number] # 区县
[district_name: string] # 小区  ==>  [microdistrict_name: string] # 小区  或者community也行
[district_code: number] # 小区  ==>  [microdistrict_code: string] # 小区 
现在用的是district表示小区subdistrict表示街道，应该改为区、街道、小区分别用district、subdistrict、microdistrict (community)。

[facility: string] # 房屋设施。选项中增加一项饮水机，1. 空调， 2. 电视， 3. 洗衣机， 4. 冰箱， 5. 微波炉， 6. 饮水机， 7. 热水淋浴， 8.有线网络， 9. 无线网络， 10. 暖气， 11 门禁系统， 12. 电梯， 13. 停车位; 1|2|3

[rent_room_type: number] # 出租方式，整租1 主卧2 次卧3
