### ISSUE TITLE
添加房源照片

### ISSUE THREAD

**Issue by QiDekang** [why2012/QSZ#15]
是否能一次添加多张？

### 参数

    house_id: number
    house_photo: file
    //  新增
    rooms_type: number   //  房间类型： 1. 主卧， 2. 次卧， 3. 客厅， 4. 厨房， 5. 卫生间， 6. 阳台， 7. 其他房间
    rooms_area: number  //  房间的面积，只有主卧、次卧类型的房间有这一字段
    rooms_orientation: string  //  房间的朝向，只有主卧、次卧类型的房间有这一字段，房间内最大采光面即窗户的朝向。

**Comment by why2012** [comment]
done.
