### ISSUE TITLE
搜索房源

### ISSUE THREAD

**Issue by QiDekang** [why2012/QSZ#16]
### 参数
    [house_name: string] # 房屋介绍标题
    //  修改含义
    [house_rooms: number] # 户型（例如三居）（支持多选），卧室数量，与house_type（例如三室一厅一厨一卫）不同。
    //  可删除该项，目前不做短租业务。  [house_rent_time_type: number] # 类型，1 短租, 2 长租
    [house_rent_room_type: number] # 类型（支持多选），1 整租, 2 单间
    //  修改区间形式，通过滑动滑块选择上下限，步长为100。从0起步，1w及以上为不限
    [house_rent_fee: string] # 租金
    //  修改选项
    [house_source: number] # 来源（支持多选），1. 房东直租， 2. 二房东合租， 3.租客租期内转租
    [house_size: number] # 面积（支持多选）, [20, 50] [,100] [100,]
    [house_direction: string] # 朝向（支持多选）
    [house_decoration: string] # 装修情况（支持多选）
    [radius: number] # 筛选距离半径（单选）, km
    [shift: number] # 筛选偏移, 返回[shift:]区间内的查询结果, 默认0
    [count: number] # 筛选数目
    [sort: number] # 排序（单选）， 1 距离升，2 时间降，3 关注度降，4 租金升， 5 租金降 6 面积升
    longitude: number # 经度
    latitude: number # 纬度
    //  新增
    [subdistrict_code：number] # 按街道筛选（单选），数据参考：https://github.com/QiDekang/baijuyeyi/tree/master/src/common/data/beijing_subdistrict_subway.json
    [subway_station_code: number] #按地铁站筛选（单选），数据参考：https://github.com/QiDekang/baijuyeyi/tree/master/src/common/data/beijing_subdistrict_subway.json
    [house_characteristic: string] # 房源特色（支持多选），可选值：离地铁近、首次出租、租金月付、视频看房、独立阳台、独立供暖、独立卫生间、有电梯、有无线网

**Comment by why2012** [comment]
1、区间
就是，自己可以选择搜索范围，随便什么区间都可以，你是不是理解错了。要用滑块的话自己适配接口格式

2、啥意思？[house_name: string] # 房屋介绍标题 //  修改含义

3、Done.  [house_rent_room_type: number] # 类型（支持多选），1 整租, 2 单间

4、Done. [house_source: number] # 来源（支持多选），1. 房东直租， 2. 二房东合租， 3.租客租期内转租

5、Done.[house_direction: string] # 朝向（支持多选）

6、Done.[house_decoration: string] # 装修情况（支持多选）

7、Done.[house_rooms: number] # 户型（例如三居）（支持多选），卧室数量

8、忽略就可以了。 可删除该项，目前不做短租业务。  [house_rent_time_type: number] # 类型，1 短租, 2 长租

9、同1。//  修改区间形式，通过滑动滑块选择上下限，步长为100。从0起步，1w及以上为不限[house_rent_fee: string] # 租金

10、[house_source: number] # 来源（支持多选），1. 房东直租， 2. 二房东合租， 3.租客租期内转租

11、区间的意思就是一个范围，啥多选？[house_size: number] # 面积（支持多选）, [20, 50] [,100] [100,]

**Comment by why2012** [comment]
12、Done . [subdistrict_code：number] # 按街道筛选（单选）

13、Done . [subway_station_code: number] #按地铁站筛选
14、Done . [house_characteristic: string] # 房源特色

**Comment by QiDekang** [comment]
第1. 9.和11.
 区间这个问题我当时以为你穷举了所有可选的区间，现在仔细看发现你只是举了几个例子。
2. 
//  修改含义 
这句话是注释下面那一行house_rooms的，写注释的习惯不同。
