### ISSUE TITLE
post无法提交file相关参数

### ISSUE THREAD

**Issue by QiDekang** [why2012/QSZ#18]
### 错误信息
    msg: "file param portrait is None"
    status: 2

[错误信息](https://raw.githubusercontent.com/QiDekang/feedback/master/Bugs/file/x-www-form-urlencoded.png)

**Comment by QiDekang** [comment]
### 其他参数和图片都添加到post数据中了。其他参数后端能正常接收，但是图片收不到。我实在找不到原因了，我猜可能是后端要求的编码格式不同吧。你帮我看下代码和前端发送的数据，或者你发一下测试用的代码，我参考下。

### 附上代码
#### 发送x-www-form-urlencoded格式数据
    userInfoPostQS () {
      let config = {
        headers: {
          'token': this.token
        }
      }
      this.axios.post('/api/create_userinfo', querystring.stringify({
        nickname: 'Band',
        sex: 1,
        user_type: 1,
        self_description: 'abcdefg',
        portrait: require('../../common/icons/refrigerator-true.png')
      }), config)
      .then(response => {
        console.log(response)
      })
      .catch(function (err) {
        console.log(err)
        console.log('userInfoPost')
      })
    },
[错误信息x-www-form-urlencoded格式](https://raw.githubusercontent.com/QiDekang/feedback/master/Bugs/file/x-www-form-urlencoded.png)

提交的参数：nickname=Band&sex=1&user_type=1&self_description=abcdefg&portrait=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAALMAAACzCAYAAADCFC3zAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABOZJREFUeNrs3cFRIlkcwOF2a87o0ZtkoBuBmAEZLHvn4EYwTgTrVE0ATATDRCBmABngjSOaAPteTU%2Bt29usCDT67%2F2%2Bqi4K9TC%2B96vXr7EHjlarVQFt8IshQMwgZhAziBkxg5hBzCBmEDMt8qGtv9jTl9OT9HBRHiemulimY5qPznCxbOMveNSmezNSwDncQTr66TjT71oP6Rin4zaFPRfz%2B4q4lx5u0nGp01e7z2OXop6I%2Be23Erfp%2BE2TO%2FtcRr0U89tsKca2E3s1y9u0FPRUzIcNOZ8Wj1%2FYE47bfMGz5QVx%2F4Vrisd09CIGHS7mF0LOK8t1G%2FZ%2FBxjHfrlFO2tL0KFiLleX6ZoJ%2BJQG%2F0amrx7TPGYf15zdLiKd1aL90WRUE3JeRa6EvJ1y3H4vx%2FG5s3K8rcwNrCC99HBX860r24q9bTu%2BRR7fSCtz3Srxh5D3tkLni%2BVPNd8Kc8YLsTKvWZXv0wT0ZLj3sc7XJOcRV%2BcoK%2FMg8ooRzPWG4y%2FmLfUrz2e2F41tN%2FK4zl4YfzFvedrLrysfb7B%2Fprnrk%2BNyHsS8o7pBHOutUXVnva6Yd9etORXO9dboVmO64aIi5h3N5HYQj9H%2BwRFjXursIKZiBjGDmEHMiBnEDGIGMSNmEDOIGcQMYkbMIGYQM2zmQ5t%2FufL9NvKx7AwXt6ZbzJFDvnv2vJuCvjblthkR9SrP%2B6ZbzG3hHfbFDGIGMYOYETOIGcQMYgYxI2YQ8zv0aLrFHNW88nxiututtbeAdoaLUb7tsyjvZy6CfPwXYl4X9I0pts0AMYOYQcwgZsQM71PEl%2BbOn76cTkxd8%2BMs5uadpONSa9hmIGawzdi%2Fh3SMTF3jBkWwN86JGPPcPRfNK9%2BrL1TMthnYM4OYQcwgZsQMYgYxwy7a%2FAE9%2BYakcfHjpqT8nhm9znAxNeVW5ogGxd931x2nw0eniTmsk8pzt42KGcQMYgYxI2YQM4gZxAxiRswgZhBzc2amW8xRjYp%2Fflyau%2BbEHFNnuJinh246rtLxa%2F70KdPdbm3%2FtKn8kWkT02xlBjGDmEHMIGbEDGIGMYOYETOIGcQMYgYxI2YQM4gZxIyYQcwgZhAziBkxg5hBzCBmxAxiBjGDmEHMiBnEDGIGMSNmEDOIGcQMYkbMIGYQM4gZMYOYQcxbOTFtB3Eh5uad6%2BwgjsW8f%2FPqF56%2BnHa11pw0vnWr8lTMu6sbxJ7kGtXbZFER8yt1hosc82PlywO9Nao6vo%2FlPIh5D8aV55fpVGh1bmaL0au5LhnbM%2B%2FPqOZrN9JrxM2G4y%2FmLbcak%2FTwULM6X2tvr6tyDvmy8uX7cvzF3OA%2BLvtzzZU3rw%2B5nx4%2BRj4Dhom5XB2%2B13xrYv%2B8l5DrthLfo6zK0Vbmn6tzdbuRX9y%2Fs%2BXYaWvxrfj3H0keimCvGh2tVqtog5%2B3FZOi%2Fi9Us3RcR1pN3nAc89nstqj%2Fi2p%2BKbQX4eW40DFvEPTPVWVU%2Fsw0TcpSvKf5npY8bv3yOFvzoyFDDhvzs6DH%2FzEpvF4%2Bsw0ihhxxz%2Fz8gnBarjRfNbgXn6OuyOFX5pr9X76QudTkq93nsWvDdUYrYq5sPQYv7An5cU2Rt2ijyCtxq2OuhN1ND91yK%2BKG%2FqLIF8HTNl8QtzZm%2Fn%2F8H0DEDGIGMYOYETOIGcQMYgYxI2Z4h%2F4SYABSdVhgjb5vbQAAAABJRU5ErkJggg%3D%3D

#### 发送FormData格式数据
    userInfoPostNew () {
      let file = require('../../common/icons/refrigerator-true.png')
      let params = new FormData()  //  创建form对象
      params.append('nickname', 'Band')
      params.append('sex', 1)
      params.append('user_type', 1)
      params.append('self_description', 'abcdefg')
      params.append('portrait', file)  //  通过append向form对象添加数据
      console.log(params.get('portrait')) //  FormData私有类对象，访问不到，可以通过get判断值是否传进去
      let config = {
        headers: {
          'Content-Type': 'multipart/form-data',
          'token': this.token
        }
      }
      this.axios.post('/api/create_userinfo', params, config)  //  使用axios发送post请求
      .then(response => {
        console.log(response)
      })
      .catch(function (err) {
        console.log(err)
      })
    },
[错误信息FormData格式](https://raw.githubusercontent.com/QiDekang/feedback/master/Bugs/file/FormData.png)
console.log了图片信息，图片已经添加到FormData中了。
图片信息：

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALMAAACzCAYAAADCFC3zAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABOZJREFUeNrs3cFRIlkcwOF2a87o0ZtkoBuBmAEZLHvn4EYwTgTrVE0ATATDRCBmABngjSOaAPteTU+t29usCDT67/2+qi4K9TC+96vXr7EHjlarVQFt8IshQMwgZhAziBkxg5hBzCBmEDMt8qGtv9jTl9OT9HBRHiemulimY5qPznCxbOMveNSmezNSwDncQTr66TjT71oP6Rin4zaFPRfz+4q4lx5u0nGp01e7z2OXop6I+e23Erfp+E2TO/tcRr0U89tsKca2E3s1y9u0FPRUzIcNOZ8Wj1/YE47bfMGz5QVx/4Vrisd09CIGHS7mF0LOK8t1G/Z/BxjHfrlFO2tL0KFiLleX6ZoJ+JQG/0amrx7TPGYf15zdLiKd1aL90WRUE3JeRa6EvJ1y3H4vx/G5s3K8rcwNrCC99HBX860r24q9bTu+RR7fSCtz3Srxh5D3tkLni+VPNd8Kc8YLsTKvWZXv0wT0ZLj3sc7XJOcRV+coK/Mg8ooRzPWG4y/mLfUrz2e2F41tN/K4zl4YfzFvedrLrysfb7B/prnrk+NyHsS8o7pBHOutUXVnva6Yd9etORXO9dboVmO64aIi5h3N5HYQj9H+wRFjXursIKZiBjGDmEHMiBnEDGIGMSNmEDOIGcQMYkbMIGYQM2zmQ5t/ufL9NvKx7AwXt6ZbzJFDvnv2vJuCvjblthkR9SrP+6ZbzG3hHfbFDGIGMYOYETOIGcQMYgYxI2YQ8zv0aLrFHNW88nxiututtbeAdoaLUb7tsyjvZy6CfPwXYl4X9I0pts0AMYOYQcwgZsQM71PEl+bOn76cTkxd8+Ms5uadpONSa9hmIGawzdi/h3SMTF3jBkWwN86JGPPcPRfNK9+rL1TMthnYM4OYQcwgZsQMYgYxwy7a/AE9+YakcfHjpqT8nhm9znAxNeVW5ogGxd931x2nw0eniTmsk8pzt42KGcQMYgYxI2YQM4gZxAxiRswgZhBzc2amW8xRjYp/flyau+bEHFNnuJinh246rtLxa/70KdPdbm3/tKn8kWkT02xlBjGDmEHMIGbEDGIGMYOYETOIGcQMYgYxI2YQM4gZxIyYQcwgZhAziBkxg5hBzCBmxAxiBjGDmEHMiBnEDGIGMSNmEDOIGcQMYkbMIGYQM4gZMYOYQcxbOTFtB3Eh5uad6+wgjsW8f/PqF56+nHa11pw0vnWr8lTMu6sbxJ7kGtXbZFER8yt1hosc82PlywO9Nao6vo/lPIh5D8aV55fpVGh1bmaL0au5LhnbM+/PqOZrN9JrxM2G4y/mLbcak/TwULM6X2tvr6tyDvmy8uX7cvzF3OA+LvtzzZU3rw+5nx4+Rj4Dhom5XB2+13xrYv+8l5DrthLfo6zK0Vbmn6tzdbuRX9y/s+XYaWvxrfj3H0keimCvGh2tVqtog5+3FZOi/i9Us3RcR1pN3nAc89nstqj/i2p+KbQX4eW40DFvEPTPVWVU/sw0TcpSvKf5npY8bv3yOFvzoyFDDhvzs6DH/zEpvF4+sw0ihhxxz/z8gnBarjRfNbgXn6OuyOFX5pr9X76QudTkq93nsWvDdUYrYq5sPQYv7An5cU2Rt2ijyCtxq2OuhN1ND91yK+KG/qLIF8HTNl8QtzZm/n/8H0DEDGIGMYOYETOIGcQMYgYxI2Z4h/4SYABSdVhgjb5vbQAAAABJRU5ErkJggg==

**Comment by why2012** [comment]
你这是哪个接口？不要把文件用base64序列化，用form方式上传。装一个postman，用js调接口前先用postman调一遍

**Comment by QiDekang** [comment]
接口是：http://www.baijuyeyi.com:20001/create_userinfo

/api/create_userinfo中api代表http://www.baijuyeyi.com:20001

其他接口也试过，是一样的问题。



我用postman试试

**Comment by QiDekang** [comment]
已解决，可以关了
